### ISSUE TITLE
bert 和 roberta对于模型提升的问题

### ISSUE THREAD

**Issue by upccpu** [TIAN-viola/DynRT#2]
你好，你的这篇工作很有意思。我也在进行多模态反讽方面的研究。我有个疑问，你在论文里汇报的关于hkemodel的工作要比原论文中的高出了很多。我看文章中提到你复现的结果是基于roberta和vit。而hkemodel本身是基于bert和vit的。我想咨询一下roberta作为text 特征提取器是不是相较于bert能够提升很多？同时，你能不能给我一下你这个模型用bert能够得出的结果呢？

非常感谢！

**Comment by TIAN-viola** [comment]
感谢你的关注与提问！

根据经验，RoBERTa的文本编码能力比BERT强。为了达到更好的性能，我们的工作在一开始就使用了RoBERTa作为text encoder。

在审稿过程中，审稿人指出了我们的模型使用的text encoder和vision encoder与baselines不同，为了公平比较，建议将部分baseline的encoder改为我们所使用的的RoBERTa与ViT。因此我们将以往的SOTA工作hkemodel的text encoder换为RoBERTa（hkemodel原论文中的vision encoder是ViT）,并将相应实验结果在最终版论文中进行了汇报。hkemodel的实验结果表明RoBERTa在多模态反讽任务中的表现的确比BERT好。

根据hkemodel的实验经验，DynRT-Net(BERT)的性能估计会比DynRT-Net(RoBERTa)有所下降。

小tips: 建议你们的工作中也进行自己工作与部分对比工作的encoder统一避免审稿人质疑公平性，祝好！

**Comment by upccpu** [comment]
> 感谢你的关注与提问！
> 
> 根据经验，RoBERTa的文本编码能力比BERT强。为了达到更好的性能，我们的工作在一开始就使用了RoBERTa作为text encoder。
> 
> 在审稿过程中，审稿人指出了我们的模型使用的text encoder和vision encoder与baselines不同，为了公平比较，建议将部分baseline的encoder改为我们所使用的的RoBERTa与ViT。因此我们将以往的SOTA工作hkemodel的text encoder换为RoBERTa（hkemodel原论文中的vision encoder是ViT）,并将相应实验结果在最终版论文中进行了汇报。hkemodel的实验结果表明RoBERTa在多模态反讽任务中的表现的确比BERT好。
> 
> 根据hkemodel的实验经验，DynRT-Net(BERT)的性能估计会比DynRT-Net(RoBERTa)有所下降。
> 
> 小tips: 建议你们的工作中也进行自己工作与部分对比工作的encoder统一避免审稿人质疑公平性，祝好！

好的，谢谢回复。我们测试了将bert换成roberta，acc的结果的确会提升2-3个百分点左右。预祝你以后还能有好的工作，再次感谢。
